/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnnyRouteImport } from './routes/unny'
import { Route as RisoletaRouteImport } from './routes/risoleta'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LumeRouteImport } from './routes/lume'
import { Route as LouvaldoRouteImport } from './routes/louvaldo'
import { Route as LilaRouteImport } from './routes/lila'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LouvaldoViolaoRouteImport } from './routes/louvaldo.violao'
import { Route as LouvaldoBateriaRouteImport } from './routes/louvaldo.bateria'
import { Route as LilaRankingRouteImport } from './routes/lila.ranking'
import { Route as LilaQuizRouteImport } from './routes/lila.quiz'
import { Route as LilaPerfilRouteImport } from './routes/lila.perfil'
import { Route as LilaJornadaRouteImport } from './routes/lila.jornada'

const UnnyRoute = UnnyRouteImport.update({
  id: '/unny',
  path: '/unny',
  getParentRoute: () => rootRouteImport,
} as any)
const RisoletaRoute = RisoletaRouteImport.update({
  id: '/risoleta',
  path: '/risoleta',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LumeRoute = LumeRouteImport.update({
  id: '/lume',
  path: '/lume',
  getParentRoute: () => rootRouteImport,
} as any)
const LouvaldoRoute = LouvaldoRouteImport.update({
  id: '/louvaldo',
  path: '/louvaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const LilaRoute = LilaRouteImport.update({
  id: '/lila',
  path: '/lila',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LouvaldoViolaoRoute = LouvaldoViolaoRouteImport.update({
  id: '/violao',
  path: '/violao',
  getParentRoute: () => LouvaldoRoute,
} as any)
const LouvaldoBateriaRoute = LouvaldoBateriaRouteImport.update({
  id: '/bateria',
  path: '/bateria',
  getParentRoute: () => LouvaldoRoute,
} as any)
const LilaRankingRoute = LilaRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => LilaRoute,
} as any)
const LilaQuizRoute = LilaQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LilaRoute,
} as any)
const LilaPerfilRoute = LilaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => LilaRoute,
} as any)
const LilaJornadaRoute = LilaJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => LilaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jornada': typeof JornadaRoute
  '/lila': typeof LilaRouteWithChildren
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/play': typeof PlayRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/lila/jornada': typeof LilaJornadaRoute
  '/lila/perfil': typeof LilaPerfilRoute
  '/lila/quiz': typeof LilaQuizRoute
  '/lila/ranking': typeof LilaRankingRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
  '/louvaldo/violao': typeof LouvaldoViolaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jornada': typeof JornadaRoute
  '/lila': typeof LilaRouteWithChildren
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/play': typeof PlayRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/lila/jornada': typeof LilaJornadaRoute
  '/lila/perfil': typeof LilaPerfilRoute
  '/lila/quiz': typeof LilaQuizRoute
  '/lila/ranking': typeof LilaRankingRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
  '/louvaldo/violao': typeof LouvaldoViolaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jornada': typeof JornadaRoute
  '/lila': typeof LilaRouteWithChildren
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/play': typeof PlayRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/lila/jornada': typeof LilaJornadaRoute
  '/lila/perfil': typeof LilaPerfilRoute
  '/lila/quiz': typeof LilaQuizRoute
  '/lila/ranking': typeof LilaRankingRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
  '/louvaldo/violao': typeof LouvaldoViolaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jornada'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/play'
    | '/risoleta'
    | '/unny'
    | '/lila/jornada'
    | '/lila/perfil'
    | '/lila/quiz'
    | '/lila/ranking'
    | '/louvaldo/bateria'
    | '/louvaldo/violao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jornada'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/play'
    | '/risoleta'
    | '/unny'
    | '/lila/jornada'
    | '/lila/perfil'
    | '/lila/quiz'
    | '/lila/ranking'
    | '/louvaldo/bateria'
    | '/louvaldo/violao'
  id:
    | '__root__'
    | '/'
    | '/jornada'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/play'
    | '/risoleta'
    | '/unny'
    | '/lila/jornada'
    | '/lila/perfil'
    | '/lila/quiz'
    | '/lila/ranking'
    | '/louvaldo/bateria'
    | '/louvaldo/violao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JornadaRoute: typeof JornadaRoute
  LilaRoute: typeof LilaRouteWithChildren
  LouvaldoRoute: typeof LouvaldoRouteWithChildren
  LumeRoute: typeof LumeRoute
  PlayRoute: typeof PlayRoute
  RisoletaRoute: typeof RisoletaRoute
  UnnyRoute: typeof UnnyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unny': {
      id: '/unny'
      path: '/unny'
      fullPath: '/unny'
      preLoaderRoute: typeof UnnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risoleta': {
      id: '/risoleta'
      path: '/risoleta'
      fullPath: '/risoleta'
      preLoaderRoute: typeof RisoletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lume': {
      id: '/lume'
      path: '/lume'
      fullPath: '/lume'
      preLoaderRoute: typeof LumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louvaldo': {
      id: '/louvaldo'
      path: '/louvaldo'
      fullPath: '/louvaldo'
      preLoaderRoute: typeof LouvaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lila': {
      id: '/lila'
      path: '/lila'
      fullPath: '/lila'
      preLoaderRoute: typeof LilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louvaldo/violao': {
      id: '/louvaldo/violao'
      path: '/violao'
      fullPath: '/louvaldo/violao'
      preLoaderRoute: typeof LouvaldoViolaoRouteImport
      parentRoute: typeof LouvaldoRoute
    }
    '/louvaldo/bateria': {
      id: '/louvaldo/bateria'
      path: '/bateria'
      fullPath: '/louvaldo/bateria'
      preLoaderRoute: typeof LouvaldoBateriaRouteImport
      parentRoute: typeof LouvaldoRoute
    }
    '/lila/ranking': {
      id: '/lila/ranking'
      path: '/ranking'
      fullPath: '/lila/ranking'
      preLoaderRoute: typeof LilaRankingRouteImport
      parentRoute: typeof LilaRoute
    }
    '/lila/quiz': {
      id: '/lila/quiz'
      path: '/quiz'
      fullPath: '/lila/quiz'
      preLoaderRoute: typeof LilaQuizRouteImport
      parentRoute: typeof LilaRoute
    }
    '/lila/perfil': {
      id: '/lila/perfil'
      path: '/perfil'
      fullPath: '/lila/perfil'
      preLoaderRoute: typeof LilaPerfilRouteImport
      parentRoute: typeof LilaRoute
    }
    '/lila/jornada': {
      id: '/lila/jornada'
      path: '/jornada'
      fullPath: '/lila/jornada'
      preLoaderRoute: typeof LilaJornadaRouteImport
      parentRoute: typeof LilaRoute
    }
  }
}

interface LilaRouteChildren {
  LilaJornadaRoute: typeof LilaJornadaRoute
  LilaPerfilRoute: typeof LilaPerfilRoute
  LilaQuizRoute: typeof LilaQuizRoute
  LilaRankingRoute: typeof LilaRankingRoute
}

const LilaRouteChildren: LilaRouteChildren = {
  LilaJornadaRoute: LilaJornadaRoute,
  LilaPerfilRoute: LilaPerfilRoute,
  LilaQuizRoute: LilaQuizRoute,
  LilaRankingRoute: LilaRankingRoute,
}

const LilaRouteWithChildren = LilaRoute._addFileChildren(LilaRouteChildren)

interface LouvaldoRouteChildren {
  LouvaldoBateriaRoute: typeof LouvaldoBateriaRoute
  LouvaldoViolaoRoute: typeof LouvaldoViolaoRoute
}

const LouvaldoRouteChildren: LouvaldoRouteChildren = {
  LouvaldoBateriaRoute: LouvaldoBateriaRoute,
  LouvaldoViolaoRoute: LouvaldoViolaoRoute,
}

const LouvaldoRouteWithChildren = LouvaldoRoute._addFileChildren(
  LouvaldoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JornadaRoute: JornadaRoute,
  LilaRoute: LilaRouteWithChildren,
  LouvaldoRoute: LouvaldoRouteWithChildren,
  LumeRoute: LumeRoute,
  PlayRoute: PlayRoute,
  RisoletaRoute: RisoletaRoute,
  UnnyRoute: UnnyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
