/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnnyRouteImport } from './routes/unny'
import { Route as RisoletaRouteImport } from './routes/risoleta'
import { Route as LumeRouteImport } from './routes/lume'
import { Route as LouvaldoRouteImport } from './routes/louvaldo'
import { Route as LilaRouteImport } from './routes/lila'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LouvaldoBateriaRouteImport } from './routes/louvaldo.bateria'

const UnnyRoute = UnnyRouteImport.update({
  id: '/unny',
  path: '/unny',
  getParentRoute: () => rootRouteImport,
} as any)
const RisoletaRoute = RisoletaRouteImport.update({
  id: '/risoleta',
  path: '/risoleta',
  getParentRoute: () => rootRouteImport,
} as any)
const LumeRoute = LumeRouteImport.update({
  id: '/lume',
  path: '/lume',
  getParentRoute: () => rootRouteImport,
} as any)
const LouvaldoRoute = LouvaldoRouteImport.update({
  id: '/louvaldo',
  path: '/louvaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const LilaRoute = LilaRouteImport.update({
  id: '/lila',
  path: '/lila',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LouvaldoBateriaRoute = LouvaldoBateriaRouteImport.update({
  id: '/bateria',
  path: '/bateria',
  getParentRoute: () => LouvaldoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lila': typeof LilaRoute
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lila': typeof LilaRoute
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lila': typeof LilaRoute
  '/louvaldo': typeof LouvaldoRouteWithChildren
  '/lume': typeof LumeRoute
  '/risoleta': typeof RisoletaRoute
  '/unny': typeof UnnyRoute
  '/louvaldo/bateria': typeof LouvaldoBateriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/risoleta'
    | '/unny'
    | '/louvaldo/bateria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/risoleta'
    | '/unny'
    | '/louvaldo/bateria'
  id:
    | '__root__'
    | '/'
    | '/lila'
    | '/louvaldo'
    | '/lume'
    | '/risoleta'
    | '/unny'
    | '/louvaldo/bateria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LilaRoute: typeof LilaRoute
  LouvaldoRoute: typeof LouvaldoRouteWithChildren
  LumeRoute: typeof LumeRoute
  RisoletaRoute: typeof RisoletaRoute
  UnnyRoute: typeof UnnyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unny': {
      id: '/unny'
      path: '/unny'
      fullPath: '/unny'
      preLoaderRoute: typeof UnnyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risoleta': {
      id: '/risoleta'
      path: '/risoleta'
      fullPath: '/risoleta'
      preLoaderRoute: typeof RisoletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lume': {
      id: '/lume'
      path: '/lume'
      fullPath: '/lume'
      preLoaderRoute: typeof LumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louvaldo': {
      id: '/louvaldo'
      path: '/louvaldo'
      fullPath: '/louvaldo'
      preLoaderRoute: typeof LouvaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lila': {
      id: '/lila'
      path: '/lila'
      fullPath: '/lila'
      preLoaderRoute: typeof LilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louvaldo/bateria': {
      id: '/louvaldo/bateria'
      path: '/bateria'
      fullPath: '/louvaldo/bateria'
      preLoaderRoute: typeof LouvaldoBateriaRouteImport
      parentRoute: typeof LouvaldoRoute
    }
  }
}

interface LouvaldoRouteChildren {
  LouvaldoBateriaRoute: typeof LouvaldoBateriaRoute
}

const LouvaldoRouteChildren: LouvaldoRouteChildren = {
  LouvaldoBateriaRoute: LouvaldoBateriaRoute,
}

const LouvaldoRouteWithChildren = LouvaldoRoute._addFileChildren(
  LouvaldoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LilaRoute: LilaRoute,
  LouvaldoRoute: LouvaldoRouteWithChildren,
  LumeRoute: LumeRoute,
  RisoletaRoute: RisoletaRoute,
  UnnyRoute: UnnyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
